### ISSUE TITLE
Garisson Building doesn´t work

### ISSUE THREAD

**Issue by Montiemedia** [RevoArma3/3denEnhanced#50]
Hi,

the Garisson in Buildung Feature doesn´t work. Following message from RPT File
I tried to Garisson a CSAT Rifle Squad. Map is Altis.

[bug.txt](https://github.com/RevoArma3/3denEnhanced/files/238474/bug.txt)

**Comment by RevoArma3** [comment]
Thanks for the report, I'll investigate the issue.

**Comment by RevoArma3** [comment]
Was fixed with the overhaul of the garrison functionality
